#
# This file is automatically generated by the Terraform inventory module
#
---
all:
  vars:
    vcenter:
      host: ${ vsphere_server }
      username: ${ user }
      password: ${ password }
      allow_unverified_ssl: ${ allow_unverified_ssl }

  hosts:
%{ for item in vms ~}%{ for types in item ~}%{ for vm in types ~}
    ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
      hostname: ${ vm.name }
      uuid: ${ vm.id }
      fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
%{ endfor ~}
%{ endfor ~}
%{ endfor ~}

  children:
    mssql_linux_vm:
      hosts:
%{ for item in vms ~}%{ for vm in item.mssql_linux ~}
        ${ vm.clone[0].customize[0].network_interface[0].ipv4_address }:
          mssql_linux_vm:
            hostname: ${ vm.name }
            uuid: ${ vm.id }
            fqdn: ${ vm.clone[0].customize[0].linux_options[0].host_name }.${ vm.clone[0].customize[0].linux_options[0].domain }
            data_disks:
%{ for i in range(1, length(vm.disk)) ~}
                  - sd${ ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"][i] }
%{ endfor ~}
%{ endfor ~}
%{ endfor ~}

#
# EOF
#