---
- name: Update hosts file with cluster nodes
  lineinfile: dest="{{ hosts_file }}"
    state=present
    dest="{{ hosts_file }}"
    regexp='.*{{ item }}$' line="{{ \"%-13s\" | format(hostvars[item].ansible_default_ipv4.address) }}\t{{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: Comment out pipeline archive in fstab
  replace:
    dest: "{{ hosts_file }}"
    regexp: '^127.0.0.1'
    replace: '#127.0.0.1'