---
- name: Install required libraries for Ubuntu
  apt:
    name:
      - python3-selinux
      - selinux-policy-default
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  register: selinux_state

- name: Perform reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: selinux_state.changed
