---
- name: Install required libraries for Ubuntu
  ansible.builtin.apt:
    name:
      - python3-selinux
      - selinux-policy-default
    state: present
  register: apt_action
  delay: 5
  retries: 60
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  when: ansible_distribution == 'Ubuntu'

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify:
    - Reboot machine

- name: Flush handlers
  meta: flush_handlers

