---
- name: Fail on unexpected distributions
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'CentOS' or
        ansible_distribution == 'Debian' or
        ansible_distribution == 'RedHat' or
        ansible_distribution == 'Ubuntu'
    fail_msg: "Unexpected distribution: {{ ansible_distribution }}"
    success_msg: "Supported distribution"

- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat'

- name: Stop and disable ufw
  community.general.ufw:
    state: disabled
  when: ansible_distribution == 'Debian' or 
        ansible_distribution == 'Ubuntu'
