---
- name: Install required libraries for Ubuntu
  apt:
    name:
      - python3-selinux
      - selinux-policy-default
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify:
    - Reboot machine

- name: Flush handlers
  meta: flush_handlers

