---
- name: Print distribution
  debug:
    msg: "The system distribution is: {{ ansible_distribution }}"

- name: Upgrade all packages
  import_tasks: upgrade_packages.yml
  when: system_upgrade_all_packages | default(DEFAULT_SYSTEM_UPGRADE_ALL_PACKAGES)

- name: Create hosts file
  import_tasks: create_hosts_file.yml
  vars:
    ansible_group: "{{ groups['all'] }}"
    hosts_file: "{{ system_hosts_file | default(DEFAULT_SYSTEM_HOSTS_FILE) }}"
    disable_entries:
      - 127.0.1.1
  when: hosts_file_create | default(DEFAULT_SYSTEM_HOSTS_FILE_CREATE)

- name: Disable firewall
  import_tasks: disable_firewall.yml
  when: system_firewall_disable | default(DEFAULT_SYSTEM_FIREWALL_DISABLE)

- name: Disable SELinux
  import_tasks: disable_selinux.yml
  when: system_selinux_disable | default(DEFAULT_SYSTEM_SELINUX_DISABLE)

- name: Extend OS LVM
  import_tasks: extend_os_lvm.yml
  when: system_extend_os_lvm | default(DEFAULT_SYSTEM_EXTEND_OS_LVM)

- name: Partition, format, and mount data disks
  import_tasks: mount_data_disks.yml
  vars:
    data_disk_filesystem:
    data_disk_mount_option: xfs
    data_disk_mount_path: /mnt/data
  when: system_mount_data_disks | default(DEFAULT_SYSTEM_MOUNT_DATA_DISKS)

- name: Create user account
  import_tasks: create_system_user.yml
  vars:
    user_username: "{{ system_user_username | default(DEFAULT_SYSTEM_USER_USERNAME) }}"
    user_password: "{{ system_user_password | default(DEFAULT_SYSTEM_USER_PASSWORD) }}"
    ssh_key: "{{ vm_ssh_key_file }}"
  when: user_create | default(DEFAULT_SYSTEM_CREATE_USER)
