---
mssql_bin_path: /opt/mssql/bin
mssql_tools_bin_path: /opt/mssql-tools/bin

default_mssql_directory_data: /sqlnux/data
default_mssql_directory_log: /sqlnux/log
default_mssql_directory_backup: /sqlnux/backup
default_mssql_directory_dump: /sqlnux/dump
default_mssql_directory_audit: /sqlnux/audit
default_mssql_directory_errorlogs: /sqlnux/errorlogs

default_mssql_directory_user: mssql
default_mssql_directory_group: mssql
default_mssql_directory_mode: '0755'

default_mssql_error_log_filename: 'errorlog'

default_sql_coredump_type: 'full'

default_sql_agent_logging_level: 7

default_pcs_cluster_name: 'sqnux-clus01'