---
all:
  vars:
    #
    # Role: Common
    # -------------------------------------------------------------------------

    # Host packages
    # Upgrade all the system packages.
    system_upgrade_all_packages: true

    # Hosts file
    # Edit the hosts file and add entries for each system.
    system_hosts_file_create: true
    #system_hosts_file: /etc/hosts
    system_hosts_file_disable_entries: ['127.0.1.1']

    # Firewall
    # Entirely disable the firewall.
    system_firewall_disable: true

    # SELinux
    # Entirely disable SELinux on the hosts.
    system_selinux_disable: true

    # OS Disk
    # If the OS disks has been increased should the LVM be extended and use all the available space.
    system_extend_os_lvm: true
    #system_extend_os_lvm_device: /dev/sda

    # Data Disk(s)
    system_mount_data_disks: true
    system_data_disks_filesystem: xfs
    system_data_disk_mount_paths: ['/sqlnux']

    # User
    system_create_account: true
    system_create_account_username: vmware
    system_create_account_password: vmware
    #system_create_account_key_file: ~/.ssh/id_rsa.pub

    #
    # Role: MSSQL Server
    # -------------------------------------------------------------------------

    # Mandatory Parameters
    # These must be configured

    # Set the SQL Server edition or product key. Possible values include:
    #  - Evaluation
    #  - Developer
    #  - Express
    #  - Web
    #  - Standard
    #  - Enterprise
    #  - A product key
    # Ref. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
    mssql_pid: enterprise

    # Accept the EULA confirm your acceptance of the End-User Licensing Agreement.
    # Required setting for the SQL Server image.
    # Ref. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
    mssql_accept_eula: true

    # The Virtual IP for the MSSQL AG
    # This should an address in CIDR format on the same subnet at the MSSQL servers
    # '<ip>/<prefix>
    mssql_pcs_cluster_vip_cidr: '172.16.20.221/23'

    # Accounts
    #mssql_sa_password: vmware
    #mssql_install_user_username: vmware
    #mssql_install_user_password: VMware1!
    #mssql_hacluster_password: VMware1!
    #mssql_pacemaker_username: paceuser
    #mssql_pacemaker_password: pacepass

    # Components
    #mssql_install_agent: true
    #mssql_install_ha: true
    #mssql_install_fulltext: true
    #mssql_install_intg_svc: true
    #mssql_install_ext: true # Todo
    #mssql_install_ha_pacemaker: true # Todo

    # Network
    #mssql_port: 1433

    # MSSQL server directories
    #mssql_directory_data: /sqlnux/data
    #mssql_directory_log: /sqlnux/log
    #mssql_directory_backup: /sqlnux/backup
    #mssql_directory_dump: /sqlnux/dump
    #mssql_directory_audit: /sqlnux/audit
    #mssql_directory_errorlogs: /sqlnux/errorlogs
    #mssql_directory_cert: /var/opt/mssql/data
    #mssql_error_log_filename: errorlog
    #mssql_telemetry_user_requested_local_audit_directory: /sqlnux/audit

    # Directory owner, group, and permissions
    #mssql_directory_user: mssql
    #mssql_directory_group: mssql
    #mssql_directory_mode: '0755'

    # MSSQL core dump
    # values: mini, miniplus, filtered, full
    #mssql_coredump_type: 'full'

    # MSSQL Agent
    #mssql_install_agent_enable: true
    #mssql_install_agent_error_log_file: /sqlnux/errorlogs

    # SQL Agent logging level
    # The level is a bitmask with values that equal:
    #    1 = Errors
    #    2 = Warnings
    #    4 = Info
    # If you want to capture all levels, use 7 as the value.
    #mssql_agent_logging_level: 7

    # MSSQL Trace Flags
    #mssql_trace_flags: ['1204', '1222']

    # Telemetry
    #mssql_telemetry_customer_feedback: false

    # MSSQL AG
    #mssql_ag_name: ag1
    #mssql_ag_db_name: db1
    #mssql_ag_endpoint: hadr_endpoint1

    # MSSQL PCS
    #mssql_pcs_cluster_name: pcscluster1
    #mssql_pcs_resource_vip_name: vip1
    #mssql_pcs_fence_name: vmw_fence1
