---
#
# Firewall Ports
# Todo
# - set as variables
- name: Set the firewall ports variable
  set_fact:
    firewall_ports:
      - { port: 2224, proto: "tcp" }
      - { port: 3121, proto: "tcp" }
      - { port: 5022, proto: "tcp" }
      - { port: 5405, proto: "udp" }
      - { port: 21064, proto: "tcp" }

- name: Configure firewall Ubuntu
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ firewall_ports }}"
  when: ansible_distribution == 'Ubuntu'

- name: Configure firewall CentOS/RedHat
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_ports }}"
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat'

#
# Enable HA Health Monitoring TransactSQL
# Todo: should this be started also?
- name: Enable HA Health Monitoring
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "ALTER EVENT SESSION AlwaysOn_health ON SERVER WITH (STARTUP_STATE=ON);"
  register: result

- name: Output
  ansible.builtin.debug:
    var: result.stdout

#
# Create the MSSQL Availability Group on the Primary Node
# we might need to switch the first item to hostname and second to fqdn
- name: Build node parameters
  set_fact:
    ag_node_parameters: >
      {{ ag_node_parameters | default("") }}N'{{ item.0 }}' WITH (ENDPOINT_URL = N'tcp://{{ item.1 }}:{{ mssql_endpoint_listener_port | default(default_mssql_endpoint_listener_port) }}', AVAILABILITY_MODE = {{ 'SYNCHRONOUS_COMMIT' if index < 3 else 'ASYNCHRONOUS_COMMIT' }}, FAILOVER_MODE = EXTERNAL, SEEDING_MODE = AUTOMATICBACKUP_PRIORITY = 50, SECONDARY_ROLE(ALLOW_CONNECTIONS = READ_ONLY)
  with_together:
    - "{{ groups['mssql_linux_vm'] | map('extract', hostvars, 'ansible_hostname') | list }}"
    - "{{ groups['mssql_linux_vm'] | map('extract', hostvars, 'ansible_fqdn') | list }}"
  loop_control:
    index_var: index
  when: inventory_hostname == play_hosts[0]

- name: Create the mssql availability group on the primary node
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "IF NOT EXISTS (SELECT name FROM master.sys.availability_groups WHERE name = '{{ mssql_ag_name | default(default_mssql_ag_name) }}') BEGIN CREATE AVAILABILITY GROUP [{{ mssql_ag_name | default(default_mssql_ag_name) }}] WITH (DB_FAILOVER = ON, CLUSTER_TYPE = EXTERNAL, DTC_SUPPORT = NONE, AUTOMATED_BACKUP_PREFERENCE = SECONDARY_ONLY, REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 1) FOR REPLICA ON {{  ag_node_parameters.splitlines() | join(',') }}; ALTER AVAILABILITY GROUP [{{ mssql_ag_name | default(default_mssql_ag_name) }}] GRANT CREATE ANY DATABASE END;"
  register: result
  when: inventory_hostname == play_hosts[0]

#
# Join the MSSQL Availability Group on the Secondary Nodes
#
- name: Join the mssql availability group on the secondary nodes
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "IF NOT EXISTS (SELECT name FROM master.sys.availability_groups WHERE name = '{{ mssql_ag_name | default(default_mssql_ag_name) }}') BEGIN ALTER AVAILABILITY GROUP [{{ mssql_ag_name | default(default_mssql_ag_name) }}] JOIN WITH (CLUSTER_TYPE = EXTERNAL); ALTER AVAILABILITY GROUP [{{ mssql_ag_name | default(default_mssql_ag_name) }}] GRANT CREATE ANY DATABASE END;"
  register: result
  when: inventory_hostname != play_hosts[0]

#
# Grant permission to pacemaker user
# 
- name: "Grant permissions to user {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }} on Availability Group {{ mssql_ag_name | default(default_mssql_ag_name) }}"
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "GRANT ALTER, CONTROL, VIEW DEFINITION ON AVAILABILITY GROUP::{{ mssql_ag_name | default(default_mssql_ag_name) }} TO {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}; GRANT VIEW SERVER STATE TO {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }};"
  register: result

- name: Print command output
  ansible.builtin.debug:
    var: result.stdout

#
# Create Database
#
- name: "Create database {{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}"
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "IF NOT EXISTS (SELECT name from master.sys.databases WHERE name = '{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}') BEGIN CREATE DATABASE [{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}]; ALTER DATABASE [{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}] SET RECOVERY FULL END;"
  register: result
  when: inventory_hostname == play_hosts[0]

#
# Create database backup
#
- name: Delete previous database backup
  ansible.builtin.file:
    path: "{{ mssql_directory_backup | default(default_mssql_directory_backup) }}/{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}.bak"
    state: absent
  when: inventory_hostname == play_hosts[0]

- name: "Backup database {{ mssql_ag_db_name | default(default_mssql_ag_db_name) }} to {{ mssql_directory_backup | default(default_mssql_directory_backup) }}/{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}.bak"
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "BACKUP DATABASE [{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}] TO DISK = N'{{ mssql_directory_backup | default(default_mssql_directory_backup) }}/{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}.bak'"
  register: result
  when: inventory_hostname == play_hosts[0]

#
# Add Database to Availability Group
#
- name: "Add database {{ mssql_ag_db_name | default(default_mssql_ag_db_name) }} to availability group {{ mssql_ag_name | default(default_mssql_ag_name) }}"
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "IF NOT EXISTS (SELECT AGDatabases.database_name AS name FROM sys.dm_hadr_availability_group_states States INNER JOIN master.sys.availability_groups Groups ON States.group_id = Groups.group_id INNER JOIN sys.availability_databases_cluster AGDatabases ON Groups.group_id = AGDatabases.group_id WHERE primary_replica = @@Servername AND AGDatabases.database_name = '{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}') BEGIN ALTER AVAILABILITY GROUP [{{ mssql_ag_name | default(default_mssql_ag_name) }}] ADD DATABASE [{{ mssql_ag_db_name | default(default_mssql_ag_db_name) }}] END;"
  register: result
  when: inventory_hostname == play_hosts[0]
