---
- name: Ensure pacemaker, corsync, and pcsd service are started and enabled
  ansible.builtin.service:
    name: "{{ item  }}"
    state: started
    enabled: yes
  loop:
    - pacemaker
    - corosync
    - pcsd
