---
#
# Install Pacemaker, PCS. Fence Agents and Resource Agents
#
# re: apt upgrade full raises a "Could not get lock /var/lib/dpkg/lock-frontend"
# https://github.com/ansible/ansible/issues/51663
- name: Install pacemaker and pcs
  ansible.builtin.apt:
    name:
      - pacemaker
      - pcs
      - fence-agents
      - resource-agents
    state: present
  register: apt_action
  delay: 5
  retries: 60
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Start and enable pcsd service
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: yes

- name: Stop default cluster
  ansible.builtin.command: "pcs cluster stop --force"
  register: result

- name: Destroy default cluster
  ansible.builtin.command: "pcs cluster destroy"
  register: result

- name: Set user hacluster user password
  user:
    name: hacluster
    password: "{{ (mssql_hacluster_password | default(default_mssql_hacluster_password)) | password_hash('sha512') }}"

#
# Create Pacemaker User
#
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-create-availability-group?view=sql-server-ver15
- name: "Create MSSQL user {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }} for Pacemaker"
  ansible.builtin.command: >
    {{ mssql_tools_bin_path }}/sqlcmd 
    -s localhost 
    -U SA 
    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
    -Q "IF NOT EXISTS (SELECT name FROM master.sys.server_principals WHERE name = '{{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}') BEGIN CREATE LOGIN [{{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}] with PASSWORD = N'{{ mssql_pacemaker_password | default(default_mssql_pacemaker_password) }}' END; ALTER SERVER ROLE [sysadmin] ADD MEMBER [{{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}];"
  register: result

- name: Print command output
  ansible.builtin.debug:
    var: result.stdout

#- name: "Grant permissions to user {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }} on Availability Group {{ mssql_ag_name | default(default_mssql_ag_name) }}"
#  ansible.builtin.command: >
#    {{ mssql_tools_bin_path }}/sqlcmd 
#    -s localhost 
#    -U SA 
#    -P "{{ mssql_sa_password | default(default_mssql_sa_password) }}"
#    -Q "GRANT ALTER, CONTROL, VIEW DEFINITION ON AVAILABILITY GROUP::{{ mssql_ag_name | default(default_mssql_ag_name) }} TO {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}; GRANT VIEW SERVER STATE TO {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }};"
#  register: result

- name: Print command output
  ansible.builtin.debug:
    var: result.stdout

- name: Save credentials for pacemaker login
  copy:
    dest: /var/opt/mssql/secrets/passwd
    mode: 400
    owner: root
    group: root
    content: |
      {{ mssql_pacemaker_username | default(default_mssql_pacemaker_username) }}
      {{ mssql_pacemaker_password | default(default_mssql_pacemaker_password) }}
