---
- name: Set distribution
  set_fact:
    is_centos: "{{ ansible_distribution == 'CentOS' }}"
    is_debian: "{{ ansible_distribution == 'Debian' }}"
    is_redhat: "{{ ansible_distribution == 'RedHat' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"

- name: Install MSSQL Server CentOS
  import_tasks: install_mssql_server_centos.yml
  when: is_centos

- name: Install MSSQL Server Ubuntu
  import_tasks: install_mssql_server_ubuntu.yml
  when: is_ubuntu

- name: Configure MSSQL Server
  import_tasks: configure_mssql.yml

- name: Generate MSSQL SSL certificate and configure endpoints
  import_tasks: configure_mssql_ssl_certificates.yml

- name: Configure Pacemaker on all nodes
  import_tasks: configure_pacemaker_all.yml

- name: Configure Pacemaker on the primary node
  import_tasks: configure_pacemaker_primary.yml
  when: inventory_hostname == play_hosts[0]

- name: Configure MSSQL Availability Group
  import_tasks: configure_mssql_ag.yml

- name: Configure Pacemaker AG resource on the primary node
  import_tasks: configure_pacemaker_ag.yml
  when: inventory_hostname == play_hosts[0]
