---
- name: Restart MSSQL Server
  ansible.builtin.service:
    name: mssql-server
    sleep: 5
    state: restarted

# https://github.com/mikecali/mssql2019-roles-RHEL8/blob/main/site.yaml
- name: Wait up to 60 seconds for server to become available after creation
  wait_for:
    port: 1433
    timeout: 60
