---
- name: Check if the path exists
  ansible.builtin.stat:
    path: "{{ error_log_file }}"
    get_md5: no
  register: stat_error_log_directory

- name: Ensure the audit directory parameter is valid
  assert:
    that:
    - stat_error_log_directory.stat.exists
    - stat_error_log_directory.stat.isdir
    fail_msg: "Audit directory '{{ error_log_file }}' does not appear valid "

- name: Set the MSSQL server agent error log file
  command: "{{ mssql_bin_path }}/mssql-conf set sqlagent.errorlogfile {{ error_log_file }}"

- name: Query the MSSQL server agent settings
  command: "{{ mssql_bin_path }}/mssql-conf get sqlagent"
  register: result

# The search function does not let us build the string in the function bracket, for
# some unknown and mysterious reason. So we build the query string here and use it
# and the function is happy.
- name: Build query
  set_fact:
    query_string: "errorlogfile : {{ error_log_file }}"

- name: "Ensure the MSSQL server agent logging level is set to {{ error_log_file }}"
  assert:
    that:
      - result.rc == 0
      - result.stdout is search("{{ query_string }}")
    fail_msg: "Agent error log file is not set correctly {{ result.stdout }}"
    success_msg: "Agent error log file is set to {{ error_log_file }}"
