---
- name: Ensure the logging level is valid
  assert:
    that:
    - (logging_level|int) >= 1
    - (logging_level|int) <= 7
    fail_msg: "Logging level '{{ logging_level }}' is not valid  and should be 1-7"

- name: Set the MSSQL server agent logging level
  command: "{{ mssql_bin_path }}/mssql-conf set sqlagent.errorlogginglevel {{ logging_level }}"

- name: Query the MSSQL agent settings
  command: "{{ mssql_bin_path }}/mssql-conf get sqlagent"
  register: result

# The search function does not let us build the string in the function bracket, for
# some unknown and mysterious reason. So we build the query string here and use it
# and the function is happy.
- name: Build query
  set_fact:
    query_string: "errorlogginglevel : {{ logging_level }}"

- name: "Ensure MSSQL server agent logging level is set to {{ logging_level }}"
  assert:
    that:
      - result.rc == 0
      - result.stdout is search("{{ query_string }}")
    fail_msg: "Agent logging level is not set correctly {{ result.stdout }}"
    success_msg: "Agent logging level is set to {{ logging_level }}"
