---
- name: Create parameter string
  set_fact:
    parameter_string: "{{ 'true'|string|lower if vars.feedback_enabled else 'false'|string|lower }}"

- name: Set the MSSQL server telemetry customer feedback
  command: "{{ mssql_bin_path }}/mssql-conf set telemetry.customerfeedback {{ parameter_string }}"

- name: Query the MSSQL server telemetry settings
  command: "{{ mssql_bin_path }}/mssql-conf get telemetry"
  register: result

# The search function does not let us build the string in the function bracket, for
# some unknown and mysterious reason. So we build the query string here and use it
# and the function is happy.
- name: Build query
  set_fact:
    query_string: "customerfeedback : {{ parameter_string }}"

- name: "Ensure MSSQL server telemetry customer feedback is set to {{ parameter_string }}"
  assert:
    that:
      - result.rc == 0
      - result.stdout is search("{{ query_string }}")
    fail_msg: "Telemetry customer feedback is not set correctly {{ result.stdout }}"
    success_msg: "Telemetry customer feedback is set to {{ parameter_string }}"
