---
- name: Wait for systems to boot up
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 600 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 600

- name: Get IP
  hosts: localhost
  tasks:
    - name: Set localhost IP
      set_fact:
        repo_ip: "{{ ansible_default_ipv4.address }}"

#- name: Repo Configuration
#  hosts: all
#  any_errors_fatal: true
#  vars:
#    repo_ip: "{{ hostvars['localhost']['repo_ip'] }}"
#  roles:
#    - role: repo
#      when: vars.local_repo|bool == true#

- name: Common Configuration
  hosts: all
  any_errors_fatal: true
  roles:
    - role: common

- name: Install MSSQL
  hosts: all
  any_errors_fatal: true
  roles:
    - role: mssql_server

- name: Print Configuration Information
  ansible.builtin.debug:
    msg: |
      Cluster Information
      --------------------------------
      VIP: {{ mssql_pcs_cluster_vip_cidr | ansible.netcommon.ipaddr('address') }}
      Nodes:
      {{ groups['mssql_linux_vm'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join('\n') }}
      ================================
      
      MSSQL Information
      --------------------------------
      PID:         '{{ mssql_pid }}'
      SA Password: '{{ mssql_sa_password | default(default_mssql_sa_password) }}'
      User:        '{{ mssql_install_user_username | default(default_mssql_install_user_username) }}'
      Password:    '{{ mssql_install_user_password | default(default_mssql_install_user_password) }}'
      ================================
        
