---
- name: Enable the SQL Server Agent
  command: "{{ mssql_bin_path }}/mssql-conf set sqlagent.enabled true"

- name: Query the SQL Server Agent setting
  command: "{{ mssql_bin_path }}/mssql-conf get sqlagent"
  register: result

- name: Ensure SQL Agent is enabled
  assert:
    that:
      - result.rc == 0
      - result.stdout is search('enabled : true')
    fail_msg: "Agent is not enabled: {{ result.stdout }}"
    success_msg: "Agent status is enabled"
