---
- name: Enable MSSQL HADR
  command: "{{ mssql_bin_path }}/mssql-conf set hadr.hadrenabled  1"

- name: Query the MSSQL HADR setting
  command: "{{ mssql_bin_path }}/mssql-conf get sqlagent"
  register: result

- name: Ensure SQL Agent is enabled
  assert:
    that:
      - result.rc == 0
      - result.stdout is search('hadrenabled : 1')
    fail_msg: "Agent is not enabled: {{ result.stdout }}"
    success_msg: "Agent status is enabled"
