---
- name: Disable ufw service
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no

- name: Install pacemaker and pcs
  apt:
    name:
      - pacemaker
      - pcs
      - fence-agents
      - resource-agents
    state: present

- name: Start and enable pcsd service
  ansible.builtin.service:
    name: pcsd
    state: started
    enabled: yes

- name: Set hacluster user password
  user:
    name: hacluster
    password: "{{ HACLUSTER_PASSWORD | password_hash('sha512') }}"

- name: Create MSSQL user account for Pacemaker
  command: "{{ mssql_tools_bin_path }}/sqlcmd -s localhost -U SA -P '{{ vars.MSSQL_SA_PASSWORD }}' -Q \"CREATE LOGIN [{{ SQL_Pace_USER }}] WITH PASSWORD=N'{{ SQL_Pace_USER_PASSWORD }}', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON; ALTER SERVER ROLE [sysadmin] ADD MEMBER [{{ SQL_Pace_USER }}]\""
  register: result
  when: SQL_INSTALL_HA_Pace|upper == 'Y'

- name: Configure firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 2224, proto: "tcp" }
    - { port: 3121, proto: "tcp" }
    - { port: 21064, proto: "tcp" }
    - { port: 5405, proto: "udp" }
    - { port: 1433, proto: "tcp" }
    - { port: 5022, proto: "tcp" }

- name: Stop default cluster
  command: "pcs cluster stop --force"
  register: result

- name: Destroy default cluster
  command: "pcs cluster destroy"
  register: result
