---
- name: Ensure coredump type is valid
  assert:
    that:
    - coredump_type in ['mini', 'miniplus', 'filtered', 'full']
    fail_msg: "Coredump type '{{ coredump_type }}' does not appear valid "

- name: Set the MSSQL server agent error log file
  command: "{{ mssql_bin_path }}/mssql-conf set coredump.coredumptype {{ coredump_type }}"

- name: Query the MSSQL server agent settings
  command: "{{ mssql_bin_path }}/mssql-conf get coredump"
  register: result

# The search function does not let us build the string in the function bracket, for
# some unknown and mysterious reason. So we build the query string here and use it
# and the function is happy.
- name: Build query
  set_fact:
    query_string: "coredumptype : {{ coredump_type }}"

- name: "Ensure the MSSQL server coredump type is set to {{ coredump_type }}"
  assert:
    that:
      - result.rc == 0
      - result.stdout is search("{{ query_string }}")
    fail_msg: "Coredump type is not set correctly {{ result.stdout }}"
    success_msg: "Coredump type is set to {{ coredump_type }}"
