---
- name: Set distribution
  set_fact:
    is_centos: "{{ ansible_distribution == 'CentOS' }}"
    is_debian: "{{ ansible_distribution == 'Debian' }}"
    is_redhat: "{{ ansible_distribution == 'RedHat' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"

- name: Print distribution
  debug:
    msg: "CentOS: {{ is_centos }}\nDebian: {{ is_debian }}\nRedHat: {{ is_redhat }}\nUbuntu: {{ is_ubuntu }}"

- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: is_centos or is_redhat

- name: Stop and disable ufw
  community.general.ufw:
    state: disabled
  when: is_debian or is_ubuntu